language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install codecov
script:
  - coverage run -m unittest discover
after-success:
  - codecov