os: linux
dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install tox-travis
- pip install coverage
- pip install codecov
script:
- tox
- coverage run -m unittest discover
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: ag1lI/BZPTJWyV1NjPH0jld8jJyqYv487Iwbm88Hm6Vyewgte2x5SmI0VuLOMsHN+yh4gooa6y8lVj4RE35X0BTEVP9iCK94744vqgvbakeOjOgHiurb1SGCMn/ztRlNVNhqylk/ZlfwWpat43rOVTdzG2C0LDJSlGT3chBL4SUmh4LHZhSACpVDAPhzWFXL15ArSzW2eBp5zdDZ7wAhCv4aFXcTXF/Bz1nG9dC+rY3JJi48K8zNkbBQqpRZOX+4KNJejDHps1gAHq5RMX80iLg3fyt8dIxd9hjyFfpUFLwunhFCk3bNMhwa0KpH5a1gRiW7kXqXffXyW96OB95CQ2kMLn4T6SIOb4YWd+U0U7H8bGl3SCQXxkGH8edOJukA93efuavhJUy59MUgCdscwhMHhVAUcBPMAon1EHZo0aDp5toO/XIjklyOIQeoCztIKNUibrDLN3a4PjKKS3O8TnguiLHcXgkMLHHZJGZf7WrJ8pByXgWndzAZ+sZm3gqytytKAyJYjNHZqEcqiseBQPueDLR7cR4mMRctoOAAskxJDT1S77n6MzQDpfXlok6zhW9olC9qcPlOtzgaMZHGepQN4lSNEX9P4SmWk2MECcPb46GAmta1EnARoXNIo5cZkkPnhBVq5DJjvUl+AXCJ3BPVuh3kgNKbhT9jhTdLSV8=
  on:
    tags: true
    repo: Vipul97/slr-parser
    python: 3.8
