language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install tox-travis
  - pip install coverage
  - pip install codecov
script:
  - tox
  - coverage run -m unittest discover
after-success:
  - codecov
